--- 
apiVersion: v1
kind: Template
metadata: 
  name: thelounge
objects: 
  - 
    apiVersion: v1
    kind: Service
    metadata: 
      labels: 
        app: "${NAME}"
      name: "${NAME}"
    spec: 
      ports: 
        - 
          name: thelounge
          port: 443
          protocol: TCP
          targetPort: 9000
      selector: 
        app: "${NAME}"
      sessionAffinity: ClientIP
      type: ClusterIP
  - 
    apiVersion: v1
    kind: Route
    metadata: 
      labels: 
        app: "${NAME}"
      name: "${NAME}"
    spec: 
      port: 
        targetPort: thelounge
      tls: 
        termination: edge
      to: 
        kind: Service
        name: "${NAME}"
  - 
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata: 
      name: "${NAME}"
    spec: 
      accessModes: 
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 1Gi
  - 
    apiVersion: v1
    kind: DeploymentConfig
    metadata: 
      labels: 
        app: "${NAME}"
      name: "${NAME}"
    spec: 
      replicas: 1
      selector: 
        app: "${NAME}"
      strategy: 
        type: Recreate
      template: 
        metadata: 
          labels: 
            app: "${NAME}"
        spec: 
          containers: 
            - 
              image: "${IMAGE}"
              imagePullPolicy: "${IMAGE_PULL_POLICY}"
              livenessProbe: 
                httpGet: 
                  path: /
                  port: 9000
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 10
              name: thelounge
              readinessProbe: 
                httpGet: 
                  path: /
                  port: 9000
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 5
              volumeMounts: 
                - 
                  mountPath: /home/lounge/data
                  name: data
                  readOnly: false
          volumes: 
            - 
              name: data
              persistentVolumeClaim: 
                claimName: "${PVC}"
      triggers: 
        - 
          type: ConfigChange
parameters: 
  - 
    description: "The name of the app."
    name: NAME
    value: thelounge
  - 
    description: "The name of a PersistentVolumeClaim which will be mounted as thelounge's data directory."
    name: PVC
    value: thelounge
  - 
    description: "Image to use"
    name: IMAGE
    value: "jasonmadigan/lounge:latest"
  - 
    description: "How to handle updates to the image."
    name: IMAGE_PULL_POLICY
    value: Always
